---
- name: Install git and clone a remote repo from github
  hosts: all
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes
    - name: clone a remote repo from github
      git:
        repo: https://github.com/IntelliqDevops/FunctionalTesting.git
        dest: /tmp/mygit 
...
